/*Anderson Lima e Katia Nienow*/

SELECT * FROM db_prova.resposta;


INSERT INTO resposta(id, resposta) 
VALUES(101, 'É uma estrutura que permite armazenar e distribuir de forma inteligente tudo aquilo que é importante, como informação, para a empresa. Para que este gerenciamento de informações funcione, é necessário o SGBD - Sistema de Gerenciamento de Banco de Dados'),
	  (102, 'O SGBD é o Sistema de Gerenciamento de Banco de Dados, um conjunto de softwares que permitem que determinadas áreas de cada companhia acessem o banco de dados e usufruam das informações de acordo com a necessidade. São exemplos de SGBD os sistemas MySQL, SQLserver, PostgreSQL e DB2.'),
      (103, 'DML, DCL, DDL e DQL são subconjuntos de comandos do SQL. O DML é o Data Manipulation Language, subconjunto que define os comandos usados para manipular os dados armazenados em um banco. Os comandos mais importantes do DML são: INSERT, DELETE e UPDATE. O DCL é o Data Control Language é o subconjunto no qual encontramos comandos para controlar o acesso aos dados da nossa base. Através deste conjunto conseguimos estabelecer restrições e permissões para quem acessa o banco por meio dos comandos GRANT e REVOKE. O DDL é o Data Definition Language, um subconjunto de SQL que apresenta comandos usados para gerenciar as estrutruras do banco de dados. Com ele podemos criar, atualizar e remover objetos da base, como tabelas e índices através dos comandos CREATE, DROP e ALTER. Por fim, o DQL é o Data Query Language, responsável pela consulta de dados através do comando SELECT'), 
      (104, 'A Entidade representa um objeto do mundo real no MER, como carros, pessoas e empresas. Pode ser classificada em três tipos: 1) Entidades Fortes - Não dependem de outras para existir; 2)Entidades Fracas - Dependem de outras para exisitir; 3)Entidades Associativas - São utilizadas quando existe a necessiadade de associar uma entidade a um relacionamento.'),
      (105, 'A chave primária (Primary Key) é um identificador único de um registro na tabela, sendo que nesta chave só podem conter valores únicos e não nulos.'),
      (106, 'A chave estrangeira (Foreign Key) é uma referência à uma chave primária de uma tabela em outra tabela, permitindo, assim, que as tabelas se relacionem.'),
      (107, 'Enquanto a chave primária aceita somente valores não nulos, a chave estrangeira aceita valores nulos. Além disso, a chave estrangeira trata-se de uma referência da chave primária numa tabela. Importante referir que o tipo e o tamanho dos dados das chaves primária e estrangeira devem ser iguais.'),
      (108, 'O tipo CHAR e o tipo VARCHAR armazenam caractere, contudo, enquanto CHAR armazena dados de comprimento fixo, VARCHAR armazena dados de comprimento variável. Utilizaremos CHAR quando os tamanhos dos dados que desejamos armazenar na coluna de uma tabela são consistentes e semelhantes. Exemplo: CPF e CEP. Quando quisermos armazenar tamanhos de dados que variam consideravelmente, utilizaremos o VARCHAR. Exemplo: endereço e nome. O INT armazena dados do tipo inteiro de tamanho até 4 bytes. O DATE armazena dados referentes à data no formato YYYYY-MM-DD. O DATETIME trata-se de uma combinação de data e hora, baseado no período 24 horas, no formato YYYY-MM-DD HH:MM:SS.'),
      (109, 'TIME representa valores de hora no formato HH:MM:SS, enquanto o YEAR representa valores referentes a ano no formato de YYYY ou YY e o DATE representa valores referentes a data no formato YYYY-MM-DD. O DATETIME representará a combinação de data e hora no formato YYYY-MM-DD HH:MM:SS no intervalo de 1000-01-01 00:00:00.000000 a 9999-12-31 23:59:59.999999.'),
      (110, 'O comando DELETE é responsável por remover todo e qualquer registro do banco de dados. Este comando não é reversível, portanto deve ser usado com parcimônia.')