INSERT INTO editora (nome) VALUES ('Intriseca');
INSERT INTO editora (nome) VALUES ('Juspodivm');
INSERT INTO editora (nome) VALUES ('Ridell');
INSERT INTO editora (nome) VALUES ('Darkside');
INSERT INTO editora (nome) VALUES ('TAG');
INSERT INTO editora (nome) VALUES ('Atlas');
INSERT INTO editora (nome) VALUES ('Companhias das Letras');
INSERT INTO editora (nome) VALUES ('Rocco');
INSERT INTO editora (nome) VALUES ('Alta Books');
INSERT INTO editora (nome) VALUES ('Sextante');